### PR TITLE
update 0ad and dependencies, take 2

### LINKED ISSUE #5: Update runtime to 19.08

### PR DESCRIPTION
**Pull request by corecontingency**
Since it looks like pull request #7 is dead, here is my shot!
Fixes #5 and #6

### CODE REVIEW

**Comment by corecontingency** [comment]
Seems to be a problem with updating `boost`. If I revert to the original version (1.68.0) it compiles fine.

I will take a further look tomorrow, and try to figure why the newest version of boost is breaking it!

**Comment by marcthe12** [comment]
Seems this https://www.boost.org/doc/libs/1_72_0/libs/system/doc/html/system.html#changes_in_boost_1_69

**Comment by corecontingency** [comment]
I compiled the flatpak with `boost` 1.69.0 successfully on my computer. Tested it, and it seemed to work fine (loaded up a single player game, closed and reopened it, music worked, did not test multiplayer as I did not have anyone to test it with).

Using version 1.70.0 of `boost` or later will make 0ad not compile. Seems upstream has mostly been dead since 2018, so I guess that is why.

**Comment by corecontingency** [comment]
Wasn't sure how to use sed to add in the extra release lines, so I added in the corrected appdata.xml file manually.

**Comment by corecontingency** [comment]
Uhhh, not sure what is wrong with flathub build bot right now. Apparently it is out of space? I will try again.

bot, build

**Comment by corecontingency** [comment]
So it builds fine, but when it checks the appdata.xml it reports some formatting error on line 27 with the release tag. I have looked over it several times and can't figure out what is wrong. Any ideas?

```

Processing application com.play0ad.zeroad
Error loading AppData file: failed to parse /app/share/appdata/com.play0ad.zeroad.appdata.xml: Error on line 29 char 7: <releases> already set '​' and tried to replace with '
​  '
Error: ERROR: appstream-compose failed: Child process exited with code 1
FB: unmounting rofiles-fuse /srv/buildbot/worker/build-arm-6/build/.flatpak-builder/rofiles/rofiles-4WEr81
program finished with exit code 1
elapsedTime=1624.273105
```

**Comment by barthalion** [comment]
The upstream repository has been changed less than a week ago. Calling it dead is overstatement.

**Comment by corecontingency** [comment]
Yeah, that is what happens when I take an extremely quick glance at the last release date. Sorry about that!

**Comment by barthalion** [comment]
LGTM. Would you be interested in maintaining 0ad? Current maintainer is no longer active.

**Comment by corecontingency** [comment]
Yes, I'd love to help out!

**Comment by barthalion** [comment]
Thanks! Accept your invite here: https://github.com/flathub/com.play0ad.zeroad/invitations

And feel free to merge your PR too.

**Pull request merged**
