### PR TITLE
Update 0ad and runtime

### LINKED ISSUE #5: Update runtime to 19.08

### PR DESCRIPTION
**Pull request by marcthe12**
Fixes #5 and #6

### CODE REVIEW

**Comment by Lctrs** [comment]
You also need to update the `sha512` hash of the files.

**Comment by marcthe12** [comment]
Hmm some python error

**Comment by Lctrs** [comment]
Looks like it requires `python 2`. You can include it via https://github.com/flathub/shared-modules.

**Comment by corecontingency** [comment]
bot, build

**Comment by marcthe12** [comment]
Closed in favour of #8

**Pull request closed without merging**
